# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  name: DownloadScanner
  inputs:
    script: curl https://search.maven.org/remotecontent?filepath=com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.9.8.2/vosp-api-wrappers-java-21.9.8.2-dist.zip -o api-wrapper.zip 
  

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/*.zip' 
    destinationFolder: ./

- task: CmdLine@2
  name: UploadAndScan
  env:
    VID: $(VERACODE_ID)
    VKEY: $(VERACODE_KEY)
  inputs:
    script: java -jar VeracodeJavaAPI.jar -vid "${VID}" -vkey "${VKEY}" -action uploadandscan -version "$(build.buildNumber)" -outputfilepath "uploadAndScanResult.xml"    
