trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CmdLine@2
  name: SCAScan
  env:
    SRCCLR_API_TOKEN: $(SCA_TOKEN)
  inputs:
    script: 'curl -sSL  https://download.sourceclear.com/ci.sh | SRCCLR_CI_JSON=1 sh > sca_output.json'

- powershell: echo `jq .records[0].vulnerabilities sca_output.json`
- task: CmdLine@2
  name: ParseJson
  inputs:
    script: | 
      TEMP_OUTPUT=`jq .records[0].vulnerabilities sca_output.json`
      echo $TEMP_OUTPUT
      Write-Host "##vso[task.setvariable variable=vulnerabilities]$TEMP_OUTPUT"
      echo $(vulnerabilities)
    

- task: CmdLine@2
  name: EchoVulnerabilities
  inputs:
    script: echo $(vulnerabilities)
