
trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- task: CmdLine@2
  name: SCAScan
  env:
    SRCCLR_API_TOKEN: $(SCA_TOKEN)
  inputs:
    script: 'curl -sSL  https://download.sourceclear.com/ci.sh | SRCCLR_CI_JSON=1 sh > sca_output.json'

- task: PowerShell@2
  name: ReadJsonFile
  inputs:
    targetType: 'inline'
    script: |
      $SCA_JSON = Get-Content 'sca_output.json'
      $SCA_JSON = $SCA_JSON | ConvertFrom-Json
      $SCA_JSON = $SCA_JSON.records.vulnerabilities
      $SCA_JSON = $SCA_JSON | ConvertTo-Json -Depth 10 -Compress
      $SCA_JSON = $SCA_JSON.Replace("'", "")
      Write-Host "##vso[task.setvariable variable=VULNERABILITIES_AS_JSON;isOutput=true]$SCA_JSON"

- template : CreateWorkItems.yml  
  parameters:
    vulnerabilities_as_json: $(ReadJsonFile.VULNERABILITIES_AS_JSON)
    issue_type: 'Issue'
    organization: 'rpereira0294'
    project_name: 'Test%20Project'
    Overview_Name: 'Descricao'
    Vulnerability_Types_Name: 'Tipos de Vulnerabilidade'
    Version_Range_Name: 'Versoes Afetadas'
    Recommended_Version_Name: 'Versao Recomendada'
    CVSS_Score_Name: 'Pontuacao CVSS'
    CVE_Name: 'CVE'
    Veracode_Database_Link_Name: 'Link para o banco de dados da Veracode'

