
trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- task: CmdLine@2
  name: SCAScan
  env:
    SRCCLR_API_TOKEN: $(SCA_TOKEN)
  inputs:
    script: 'curl -sSL  https://download.sourceclear.com/ci.sh | SRCCLR_CI_JSON=1 sh > sca_output.json'

- task: PowerShell@2
  name: ReadJsonFile
  inputs:
    targetType: 'inline'
    script: |
      $SCA_OUTPUT=Get-Content 'sca_output.json'
      $SCA_OUTPUT=ConvertTo-Json $SCA_OUTPUT
      $SCA_OUTPUT=$SCA_OUTPUT.records.vulnerabilities
      $SCA_OUTPUT=ConvertFrom-Json $SCA_OUTPUT
      Write-Host "##vso[task.setvariable variable=VULNERABILITIES_AS_JSON;isOutput=true]$SCA_OUTPUT"
      $SCA_OUTPUT=""

- template : CreateWorkItems.yml
  parameters:
    vulnerabilities_as_json: "$(ReadJsonFile.VULNERABILITIES_AS_JSON)"
