
trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- task: CmdLine@2
  name: SCAScan
  env:
    SRCCLR_API_TOKEN: $(SCA_TOKEN)
  inputs:
    script: 'curl -sSL  https://download.sourceclear.com/ci.sh | SRCCLR_CI_JSON=1 sh > sca_output.json'

- template : CreateWorkItems.yml
  parameters:
    sca_content: Get-Content 'sca_output.json'
