trigger:
- master

pool:
  vmImage: ubuntu-latest

variables: 
  Vulnerabilities: ''

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CmdLine@2
  name: SCAScan
  env:
    SRCCLR_API_TOKEN: $(SCA_TOKEN)
  inputs:
    script: 'curl -sSL  https://download.sourceclear.com/ci.sh | SRCCLR_CI_JSON=1 sh > sca_output.json'

- powershell: |
    $SCA_JSON = Get-Content 'sca_output.json'
    $TEMP_OUTPUT = $SCA_JSON | ConvertFrom-Json
    $TEMP_OUTPUT = $TEMP_OUTPUT.records.vulnerabilities
    $TEMP_OUTPUT = $TEMP_OUTPUT | ConvertTo-Json -Depth 10
    Write-Host "##vso[task.setvariable variable=vulnerabilities]$TEMP_OUTPUT"
    echo Vulnerabilities on temp: $TEMP_OUTPUT
    echo "##vso[task.setvariable variable=Vulnerabilities]$TEMP_OUTPUT"  

- script: |
    echo Vulnerabilties outside: $(Vulnerabilities)