# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CmdLine@2
  name: SCAScan
  env:
    SRCCLR_API_TOKEN: $(SCA_TOKEN)
  inputs:
    script: 'curl -sSL  https://download.sourceclear.com/ci.sh | SRCCLR_CI_JSON=1 sh > sca_output.json'

- task: CmdLine@2
  name: PolicyScan
  env:
    VID: $(VERACODE_ID)
    VKEY: $(VERACODE_KEY)
  inputs:
    script: |
      curl https://search.maven.org/remotecontent?filepath=com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/21.9.8.2/vosp-api-wrappers-java-21.9.8.2-dist.zip -o api-wrapper.zip
      unzip api-wrapper.zip
      java -jar api-wrapper.jar -vid $(VID) -vkey $(VKEY) -action UploadAndScan -appname "Verademo ADO" -version $(Build.BuildId) -filepath ./target/verademo.war -createprofile false

- task: CmdLine@2
  name: PipelineScan
  env:
    VID: $(VERACODE_ID)
    VKEY: $(VERACODE_KEY)
  inputs:
    script: |
      curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      unzip pipeline-scan-LATEST.zip
      java -jar pipeline-scan.jar --veracode_api_id $(VID) --veracode_api_key $(VKEY) --file ./target/verademo.war --fail_on_severity="Very High, High"